feat: Enhanced YAML to GitHub Output Action
- Added support for CRUD formatted YAML files.
- Introduced new inputs: format_type, primary_key, and primary_value.
- Updated README.md with new functionalities and examples.

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -19,7 +19,7 @@ jobs:
       id: yaml-output-global
       uses: ./
       with:
-        file_path: "./.github/settings.yml"
+        file_path: "./.github/settings-simple-nested.yml"
 
     - name: Check global outputs and environment variables
       run: |
@@ -47,7 +47,7 @@ jobs:
       id: yaml-output-region
       uses: ./
       with:
-        file_path: "./.github/settings.yml"
+        file_path: "./.github/settings-simple-nested.yml"
         main_key: regions
         sub_key: us-west-1
 
@@ -70,5 +70,52 @@ jobs:
         fi
         if [[ "${{ steps.yaml-output-region.outputs.app-name }}" != "us-demo-app" ]]; then
           echo "Validation failed. 'app-name' output for us-west-1 is not as expected."
+          exit 1
+        fi
+        
+    - name: Run YAML to Github Output Action with CRUD format and primary key-value
+      id: yaml-output-crud-primary
+      uses: ./
+      with:
+        file_path: "./.github/settings-crud.yml"
+        format_type: "crud"
+        primary_key: "app-name"
+        primary_value: "us-demo-app"
+
+    - name: Check CRUD primary outputs and environment variables
+      run: |
+        # Check the CRUD format environment variables for primary key-value
+        if [[ "${{ env.REGION }}" != "us-west-1" ]]; then
+          echo "Validation failed. 'region' environment variable is not as expected."
+          exit 1
+        fi
+        if [[ "${{ env.ACCEPTANCE_CLUSTER_NAME }}" != "us-cluster" ]]; then
+          echo "Validation failed. 'acceptance-cluster-name' environment variable is not as expected."
+          exit 1
+        fi
+        if [[ "${{ env.PRE_PROD_CLUSTER_NAME }}" != "us-pre-cluster" ]]; then
+          echo "Validation failed. 'pre-prod-cluster-name' environment variable is not as expected."
+          exit 1
+        fi
+        if [[ "${{ env.PROD_CLUSTER_NAME }}" != "us-prod-cluster" ]]; then
+          echo "Validation failed. 'prod-cluster-name' environment variable is not as expected."
+          exit 1
+        fi
+
+        # Check the CRUD format outputs for primary key-value
+        if [[ "${{ steps.yaml-output-crud-primary.outputs.region }}" != "us-west-1" ]]; then
+          echo "Validation failed. 'region' output is not as expected."
+          exit 1
+        fi
+        if [[ "${{ steps.yaml-output-crud-primary.outputs.acceptance-cluster-name }}" != "us-cluster" ]]; then
+          echo "Validation failed. 'acceptance-cluster-name' output is not as expected."
+          exit 1
+        fi
+        if [[ "${{ steps.yaml-output-crud-primary.outputs.pre-prod-cluster-name }}" != "us-pre-cluster" ]]; then
+          echo "Validation failed. 'pre-prod-cluster-name' output is not as expected."
+          exit 1
+        fi
+        if [[ "${{ steps.yaml-output-crud-primary.outputs.prod-cluster-name }}" != "us-prod-cluster" ]]; then
+          echo "Validation failed. 'prod-cluster-name' output is not as expected."
           exit 1
         fi
