removing test temp files and refactoring gitignore and actions

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -119,3 +119,54 @@ jobs:
           echo "Validation failed. 'prod-cluster-name' output is not as expected."
           exit 1
         fi
+
+    - name: Run YAML to Github Output Action with CRUD format and top-level key 'build'
+      id: yaml-output-crud-build
+      uses: ./
+      with:
+        file_path: "./.github/settings-crud-top-level-test.yml"
+        format_type: "crud"
+        primary_key: "app-name"
+        primary_value: "us-demo-app"
+        top_level_keys: "build"
+    
+    - name: Check CRUD outputs and environment variables for top-level key 'build'
+      run: |
+        if [[ "${{ env.DOCKERFILE }}" != "Dockerfile" ]]; then
+          echo "Validation failed. 'dockerfile' environment variable is not as expected."
+          exit 1
+        fi
+
+    - name: Run YAML to Github Output Action with CRUD format and top-level key 'deployment'
+      id: yaml-output-crud-deployment
+      uses: ./
+      with:
+        file_path: "./.github/settings-crud-top-level-test.yml"
+        format_type: "crud"
+        primary_key: "app-name"
+        primary_value: "us-demo-app"
+        top_level_keys: "deployment"
+
+    - name: Check CRUD outputs and environment variables for top-level key 'deployment'
+      run: |
+        if [[ "${{ env.PRE_PROD_CLUSTER_NAME }}" != "us-pre-cluster" ]] || [[ "${{ env.PROD_CLUSTER_NAME }}" != "us-prod-cluster" ]]; then
+          echo "Validation failed. Cluster names are not as expected."
+          exit 1
+        fi
+
+    - name: Run YAML to Github Output Action with CRUD format and top-level keys 'build,deployment'
+      id: yaml-output-crud-both
+      uses: ./
+      with:
+        file_path: "./.github/settings-crud-top-level-test.yml"
+        format_type: "crud"
+        primary_key: "app-name"
+        primary_value: "us-demo-app"
+        top_level_keys: "build,deployment"
+        
+    - name: Check CRUD outputs and environment variables for top-level keys 'build,deployment'
+      run: |
+        if [[ "${{ env.DOCKERFILE }}" != "Dockerfile" ]] || [[ "${{ env.PRE_PROD_CLUSTER_NAME }}" != "us-pre-cluster" ]] || [[ "${{ env.PROD_CLUSTER_NAME }}" != "us-prod-cluster" ]]; then
+          echo "Validation failed. Either dockerfile or cluster names are not as expected."
+          exit 1
+        fi
